import re


# function to validate the email
def validate_email(email):
    # check if the email contains only one @
    # check if the email contains only one .
    # check if the email contains only alphanumeric characters, ., +, -, and _
    # check if the email contains at least one character before @
    # check if the email contains at least one character between @ and .
    # check if the email contains at least two characters after .
    # if any of the above conditions are not met, return False
    if not re.match(r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$", email):
        return False
    return True


# function to validate the password
def validate_password(password):
    # check if the password contains at least one uppercase letter
    # check if the password is at least 8 characters long
    # check if the password contains at least one lowercase letter
    # check if the password contains at least one number
    # check if the password does not contain spaces
    # if any of the above conditions are not met, return False
    if (
        not re.match(r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$", password)
        or " " in password
    ):
        return False
    return True


# list of countries
countries = [
    "afghanistan",
    "aland islands",
    "albania",
    "algeria",
    "american samoa",
    "andorra",
    "angola",
    "anguilla",
    "antarctica",
    "antigua and barbuda",
    "argentina",
    "armenia",
    "aruba",
    "australia",
    "austria",
    "azerbaijan",
    "bahamas ",
    "bahrain",
    "bangladesh",
    "barbados",
    "belarus",
    "belgium",
    "belize",
    "benin",
    "bermuda",
    "bhutan",
    "bolivia",
    "bonaire, sint eustatius and saba",
    "bosnia and herzegovina",
    "botswana",
    "bouvet island",
    "brazil",
    "british indian ocean territory ",
    "brunei darussalam",
    "bulgaria",
    "burkina faso",
    "burundi",
    "cabo verde",
    "cambodia",
    "cameroon",
    "canada",
    "cayman islands ",
    "central african republic",
    "chad",
    "chile",
    "china",
    "christmas island",
    "cocos islands ",
    "colombia",
    "comoros ",
    "congo",
    "cook islands",
    "costa rica",
    "cote d'ivoire",
    "croatia",
    "cuba",
    "curacao",
    "cyprus",
    "czechia",
    "denmark",
    "djibouti",
    "dominica",
    "dominican republic",
    "ecuador",
    "egypt",
    "el salvador",
    "equatorial guinea",
    "eritrea",
    "estonia",
    "ethiopia",
    "falkland islands",
    "faroe islands",
    "fiji",
    "finland",
    "france",
    "french guiana",
    "french polynesia",
    "french southern territories ",
    "gabon",
    "gambia ",
    "georgia",
    "germany",
    "ghana",
    "gibraltar",
    "greece",
    "greenland",
    "grenada",
    "guadeloupe",
    "guam",
    "guatemala",
    "guernsey",
    "guinea",
    "guinea-bissau",
    "guyana",
    "haiti",
    "heard island and mcdonald islands",
    "holy see",
    "honduras",
    "hong kong",
    "hungary",
    "iceland",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "ireland",
    "isle of man",
    "israel",
    "italy",
    "jamaica",
    "japan",
    "jersey",
    "jordan",
    "kazakhstan",
    "kenya",
    "kiribati",
    "korea",
    "kuwait",
    "kyrgyzstan",
    "lao people's democratic republic ",
    "latvia",
    "lebanon",
    "lesotho",
    "liberia",
    "libya",
    "liechtenstein",
    "lithuania",
    "luxembourg",
    "macao",
    "macedonia",
    "madagascar",
    "malawi",
    "malaysia",
    "maldives",
    "mali",
    "malta",
    "marshall islands ",
    "martinique",
    "mauritania",
    "mauritius",
    "mayotte",
    "mexico",
    "micronesia",
    "moldova",
    "monaco",
    "mongolia",
    "montenegro",
    "montserrat",
    "morocco",
    "mozambique",
    "myanmar",
    "namibia",
    "nauru",
    "nepal",
    "netherlands",
    "new caledonia",
    "new zealand",
    "nicaragua",
    "niger ",
    "nigeria",
    "niue",
    "norfolk island",
    "northern mariana islands ",
    "norway",
    "oman",
    "pakistan",
    "palau",
    "palestine, state of",
    "panama",
    "papua new guinea",
    "paraguay",
    "peru",
    "philippines ",
    "pitcairn",
    "poland",
    "portugal",
    "puerto rico",
    "qatar",
    "reunion",
    "romania",
    "russian federation ",
    "rwanda",
    "saint barthelemy",
    "saint helena",
    "ascension and tristan da cunha",
    "saint kitts and nevis",
    "saint lucia",
    "saint martin",
    "saint pierre and miquelon",
    "saint vincent and the grenadines",
    "samoa",
    "san marino",
    "sao tome and principe",
    "saudi arabia",
    "senegal",
    "serbia",
    "seychelles",
    "sierra leone",
    "singapore",
    "sint maarten (dutch part)",
    "slovakia",
    "slovenia",
    "solomon islands",
    "somalia",
    "south africa",
    "south georgia and the south sandwich islands",
    "south sudan",
    "spain",
    "sri lanka",
    "sudan ",
    "suriname",
    "svalbard and jan mayen",
    "swaziland",
    "sweden",
    "switzerland",
    "syrian arab republic",
    "taiwan",
    "tajikistan",
    "tanzania, united republic of",
    "thailand",
    "timor-leste",
    "togo",
    "tokelau",
    "tonga",
    "trinidad and tobago",
    "tunisia",
    "turkey",
    "turkmenistan",
    "turks and caicos islands",
    "tuvalu",
    "uganda",
    "ukraine",
    "united arab emirates ",
    "united kingdom",
    "united states minor outlying islands",
    "united states of america",
    "uruguay",
    "uzbekistan",
    "vanuatu",
    "venezuela",
    "viet nam",
    "virgin islands",
    "virgin islands",
    "wallis and futuna",
    "western sahara*",
    "yemen",
    "zambia",
    "zimbabwe",
]


# function to validate country
def validate_country(country):
    # convert country to lowercase and check if it is in the list of countries
    if country.lower() not in countries:
        # if not in list return false
        return False
    # if in list, return true
    return True
