# Generated by Django 4.2 on 2023-04-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ReachOut2Me",
            "0003_alter_userprofile_avatar_alter_userprofile_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(null=True),
        ),
    ]
