# Generated by Django 4.2 on 2023-04-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReachOut2Me', '0004_alter_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=280),
        ),
    ]
