# Generated by Django 4.2 on 2023-05-01 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReachOut2Me', '0012_userprofile_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
