# Generated by Django 4.2 on 2023-05-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ReachOut2Me", "0013_delete_friendrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
