# Generated by Django 4.2 on 2023-05-10 21:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ReachOut2Me', '0015_commentreplylike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='actor_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_actor', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='actor_object_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('follow', 'Follow'), ('message', 'Message'), ('post_like', 'Post Like'), ('comment_like', 'Comment Like'), ('comment', 'Comment'), ('reply', 'Reply')], default='follow', max_length=255),
        ),
    ]
