# Generated by Django 4.2 on 2023-05-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReachOut2Me', '0016_rename_user_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('follow', 'Follow'), ('message', 'Message'), ('post_like', 'Post Like'), ('comment', 'Comment'), ('comment_like', 'Comment Like'), ('reply', 'Reply'), ('reply_like', 'Reply')], default='follow', max_length=255),
        ),
    ]
