# Generated by Django 4.2 on 2023-05-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReachOut2Me', '0017_alter_notification_verb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
